Add debug scripts
beshleman/xen-port-tooling pull request #3
Opened 2020-01-25 18:09 UTC by beshleman

2020-01-25 18:20 UTC, pdietl requested changes

2020-01-25 18:20 UTC, pdietl commented on run.sh
> +	-it petebob/riscv:$(make --no-print-directory -C container version) \
we can refactor this make call out to a variable to make it clearer
`DOCKER_VERSION=$(make --no-print-directory -C container version)`

2020-01-25 18:23 UTC, pdietl approved these changes

2020-01-25 23:29 UTC, pdietl commented
@bobby-esh are you ready to merge this?

2020-01-26 03:34 UTC, beshleman commented
@pdietl Yessirr

2020-01-26 20:30 UTC, merged